//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALLTypeFormWithDropDown
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImageUploadWithAlltypeFormContext : DbContext
    {
        public ImageUploadWithAlltypeFormContext()
            : base("name=ImageUploadWithAlltypeFormContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_countryStateCity> tbl_countryStateCity { get; set; }
        public virtual DbSet<tbl_regis> tbl_regis { get; set; }
    }
}
